/**
 * Pure helpers for publish-assets.mjs: everything that decides what the
 * browser is allowed to see, kept apart from the file system so it can be
 * tested.
 *
 * The rule: the browser may know every track (it needs them for the search)
 * and it may download the audio of the round it is playing, but it must never
 * be able to connect one to the other. That link is the answer.
 */
import { createHmac } from "node:crypto";

/**
 * Opaque file name for a track's audio. HMAC rather than a plain hash: a plain
 * hash of a public ISRC can be recomputed by anyone, a keyed one cannot.
 *
 * Without a secret the key is the ISRC itself. That is only acceptable for
 * local development, which `assertSafeConfig` enforces.
 */
export function audioKey(isrc, secret) {
  if (!secret) return isrc;
  return createHmac("sha256", secret).update(isrc).digest("base64url").slice(0, 22);
}

/**
 * Refuses a configuration that would ship the answer: a production build, or
 * any build talking to Supabase, needs the secret. Local-only development may
 * run without it.
 */
export function assertSafeConfig({ secret, env }) {
  if (secret) return;
  if (env.VERCEL_ENV === "production") {
    throw new Error("AUDIO_KEY_SECRET is required for a production build");
  }
  if (env.VITE_SUPABASE_URL) {
    throw new Error("AUDIO_KEY_SECRET is required when Supabase is configured");
  }
}

/**
 * The track as the browser gets it. No audio path, ever. The audio key is only
 * included when there is no secret (local mode picks rounds in the browser and
 * needs it); with a secret the server hands it out one round at a time.
 */
export function publicTrack(track, key, { exposeKey }) {
  const { audio_file, deezer_id, ...rest } = track;
  return exposeKey && key ? { ...rest, audio_key: key } : rest;
}

/** Envelopes re-keyed from ISRC to audio key, dropping any without audio. */
export function rekeyPeaks(peaks, keyFor) {
  const out = {};
  for (const [isrc, values] of Object.entries(peaks)) {
    const key = keyFor(isrc);
    if (key) out[key] = values;
  }
  return out;
}

function sqlText(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlTextArray(values) {
  return `array[${values.map(sqlText).join(", ")}]::text[]`;
}

/**
 * Upsert of the playable tracks into Supabase. It contains the ISRC → audio
 * key mapping, so it is written to a git-ignored folder and pasted into the
 * SQL editor by hand. Tracks that disappeared from the catalog are removed
 * unless a round already points at them.
 */
export function seedSql(tracks) {
  if (tracks.length === 0) return "-- no playable tracks\n";
  const rows = tracks
    .map(
      (t) =>
        `  (${sqlText(t.id)}, ${sqlText(t.audioKey)}, ${sqlTextArray(t.artistSlugs)}, ${sqlText(t.title)})`
    )
    .join(",\n");
  return `-- Generated by scripts/publish-assets.mjs. Contains the answer key: never commit it.
begin;
insert into public.tracks (id, audio_key, artist_slugs, title) values
${rows}
on conflict (id) do update set
  audio_key = excluded.audio_key,
  artist_slugs = excluded.artist_slugs,
  title = excluded.title;
delete from public.tracks t
where t.id not in (${tracks.map((t) => sqlText(t.id)).join(", ")})
  and not exists (select 1 from public.rounds r where r.track_id = t.id);
commit;
`;
}
